### ISSUE TITLE
"Zijmenu" has `<nav>` inside `<main>` (not recommended)

### ISSUE THREAD

**Issue by Robbert** [minvws/nl-rdo-manon#8]
The documentation for Zijmenu states:

> 1. Voeg de class sidemenu toe aan de main.
> 2. Voeg direct binnen de main een nav toe met de gewenste inhoud.

However, the HTML spec mentions:

> To wrap the [main](https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element) content of the page (as opposed to the header, the footer, the navigation bar, and a sidebar), the `main` element is used.

…and MDN says:

> Content that is repeated across a set of documents or document sections such as sidebars, navigation links, copyright information, site logos, and search forms shouldn't be included 

So the following suggested HTML structure is opposite of what the HTML standard and MDN recommend:

```html
<main nav="sidebar">
  <nav>…</nav>
  …
</main>
```

**Comment by HeleenSG** [comment]
Cool question. And after reading your comment I realize this is something that needs to be specified in the documentation. 

The way it is used at the moment is as navigation for the main content instead of page navigation. While we keep the page navigation out of the main we do keep the additional main content specific navigation inside the main. The content of this nav isn't shared/repeated over pages or documents but content specific and therefor kept inside the main as it is part of the content. 

But that is just one use case, so we should definitely communicate the guidelines based on the html-specs and define how to use the side menu. Which also means we should add examples where the side menu isn't inside the main.

**Comment by Robbert** [comment]
I suspect that even for a "table of contents navigation" the `<nav>` is best kept outside the main. For main landmark use cases like "Reader view", "Skip to main content" et cetera you all want to ignore the navigation.

**Comment by HeleenSG** [comment]
What we need is a distinction between table of content and a side menu containing top level site navigation.
While top level site navigation is repeated over pages and part of the main navigation, the table of content is part of the content. It isn't shared over multiple pages, nor repeated over documents and it shouldn't contain any additional site elements like logo's, copyright statements,  or links to alternative resources, etc. It only refers to the content it belongs to. And as such it should stay within the content. 

For example: if anyone would only shares the content, the table of content keeps its function. It helps the user navigate the content and informs them of what to expect. However any site navigation would have lost its meaning, if the content is shared outside of the scope of the original website. 

Regarding accessibility, I wholeheartedly agree that users should be able to skip the navigation and directly go to the content. The remaining questions here are:
-  Will an aria-label on the nav suffice for screenreader users to decide if they would like to enter or skip the nav entirely? Or will a 'skip to content button' provide additional value.
- If a user uses the 'skip to content button' at the top of the site. Do they want to start at the beginning of the content (in this case the table of content)? Which might allow them to decide to skip the table of content, or to go to a specific part of the content. Or would they prefer to skip the table of content to go directly to the start of the document. 
I will relay both of these questions to an accessibility expert.  We can always offer different options and clarify the choices within the documentation. So Manon users can make an informed decision for their own project. I will discuss and update the documentation accordingly. 

Thank you for bringing this to my attention.

**Comment by HeleenSG** [comment]
Answers from an accessibility expert: 

**Q: Will an aria-label on the nav suffice for screenreader users to decide if they would like to enter or skip the nav entirely? Or will a 'skip to content button' provide additional value.**

"Ik denk dat veel screenreadergebruikers de TOC zouden skippen op basis van de nav of door van kop naar kop te navigeren. Een skiplink kan daarbij nog wel handig zijn voor toetsenbordgebruikers die niets kunnen met koppen/landmarks, maar zeker bij een korte TOC is het natuurlijk wel weer een extra tabstop. Het hoeft dus niet, maar mag natuurlijk wel"

Translation: 
"I believe most screenreader users will use the nav or the header to header navigation to skip the table of contents. A skip link can be a useful addition for keyboard users who can't navigate through headers/landmarks, however when the table of contents is short it will add an additional tab stop. In short it's not necessary but is off course allowed."

**Q: If a user uses the 'skip to content button' at the top of the site. Do they want to start at the beginning of the content (in this case the table of content)? Which might allow them to decide to skip the table of content, or to go to a specific part of the content. Or would they prefer to skip the table of content to go directly to the start of the document.**

A: "Ik zou de skiplink consistent naar het begin van de content brengen, meestal is dat je <main>-element. omdat je TOC op elke pagina anders is (want specifiek voor de pagina) zou ik die niet overslaan met de skiplink, dan loop je het risico dat mensen hem missen"

Translation: 
"I would consistently link the skip link to the beginning of the content. In most cases this would be the <main>-element. I wouldn't skip the table of contents with the skip link because the table of contents will differ on each page (because it's page specific). Otherwise you will risk people missing the table of contents." 

I will add a task to update the documentation to reflect these insights and guidelines.
